### ISSUE TITLE
Refactor the source code tree

### ISSUE THREAD

**Issue by vinitshahdeo** [CodeChefVIT/research-paper-query#2]
**The source tree layout should reflect the architecture**; as a corollary, a well-structured architecture can lead to a well-structured source tree layout.

The code must be structured in different modules/folders. For your project, I suggest you to have similar code structure - 

* assets
    - images

* css
  - custom ```your stylesheets```
  - vendor ```external stylesheets/frameworks say bootstrap```

* js
   - custom ``` your own scripts```
   - lib ``` external JS libraries say underscore.js etc. ```

* `index.html` (home page)

* `README.md`

@ISHITVAVERMA, @subhrapaladhi, Please make the changes.

**Comment by subhrapaladhi** [comment]
@vinitshahdeo I have made the changes and have put up a new pull request. 
please review it and approve it if you find it to be ok. 
Thank you.

**Comment by vinitshahdeo** [comment]
Looks fine!

Lemme close this issue.
