### ISSUE TITLE
Remove chromedriver.exe

### ISSUE THREAD

**Issue by L04DB4L4NC3R** [CodeChefVIT/research-paper-query#6]

**Comment by subhrapaladhi** [comment]
@L04DB4L4NC3R chromedriver.exe is required by selenium to automate the download process. 
Should I instead of keeping the file mention it in the requirements sections in the readme.md?

**Comment by L04DB4L4NC3R** [comment]
Yes. And add it to gitignore also

**Comment by subhrapaladhi** [comment]
ok
